/*
dmlssdb.M_NM
dmlssdb.M_SHAIN_DPT_ASC
dmlssdb.M_SHUDAI
dmlssdb.T_ATESAKI_CD
dmlssdb.T_RENRAKU
dmlssdb.T_RENRAKU_FILE
dmlssdb.T_RENRAKU_JOKYO
dmlssdb.V_ATESAKI
dmlssdb.V_DPT_MST
dmlssdb.V_JIGYOBU_MST
dmlssdb.V_SHAIN_MST
dmlssdb.V_TENPO_MST
*/

ALTER TABLE dmlssdb.M_NM  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.M_NM  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.M_NM  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.M_NM  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.M_NM  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.M_NM  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.M_SHAIN_DPT_ASC  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.M_SHAIN_DPT_ASC  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.M_SHAIN_DPT_ASC  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.M_SHAIN_DPT_ASC  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.M_SHAIN_DPT_ASC  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.M_SHAIN_DPT_ASC  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.M_SHUDAI  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.M_SHUDAI  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.M_SHUDAI  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.M_SHUDAI  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.M_SHUDAI  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.M_SHUDAI  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.T_ATESAKI_CD  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.T_ATESAKI_CD  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.T_ATESAKI_CD  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.T_ATESAKI_CD  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.T_ATESAKI_CD  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.T_ATESAKI_CD  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.T_RENRAKU  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.T_RENRAKU  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.T_RENRAKU  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.T_RENRAKU  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.T_RENRAKU  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.T_RENRAKU  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.T_RENRAKU_FILE  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.T_RENRAKU_FILE  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.T_RENRAKU_FILE  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.T_RENRAKU_FILE  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.T_RENRAKU_FILE  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.T_RENRAKU_FILE  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.T_RENRAKU_JOKYO  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.T_RENRAKU_JOKYO  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.T_RENRAKU_JOKYO  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.T_RENRAKU_JOKYO  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.T_RENRAKU_JOKYO  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.T_RENRAKU_JOKYO  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.V_ATESAKI  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.V_ATESAKI  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.V_ATESAKI  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.V_ATESAKI  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.V_ATESAKI  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.V_ATESAKI  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.V_DPT_MST  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.V_DPT_MST  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.V_DPT_MST  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.V_DPT_MST  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.V_DPT_MST  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.V_DPT_MST  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.V_JIGYOBU_MST  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.V_JIGYOBU_MST  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.V_JIGYOBU_MST  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.V_JIGYOBU_MST  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.V_JIGYOBU_MST  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.V_JIGYOBU_MST  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.V_SHAIN_MST  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.V_SHAIN_MST  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.V_SHAIN_MST  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.V_SHAIN_MST  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.V_SHAIN_MST  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.V_SHAIN_MST  ADD `VERSION` int NOT NULL DEFAULT 0;

ALTER TABLE dmlssdb.V_TENPO_MST  ADD `SYSTEM_CREATE_USER`  char(8) NOT NULL;
ALTER TABLE dmlssdb.V_TENPO_MST  ADD `SYSTEM_CREATE_DATE`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dmlssdb.V_TENPO_MST  ADD `SYSTEM_UPDATE_USER`  char(8);
ALTER TABLE dmlssdb.V_TENPO_MST  ADD `SYSTEM_UPDATE_DATE`  datetime;
ALTER TABLE dmlssdb.V_TENPO_MST  ADD `SYSTEM_LOGICAL_DELETE_FLG` char(1) NOT NULL default '0';
ALTER TABLE dmlssdb.V_TENPO_MST  ADD `VERSION` int NOT NULL DEFAULT 0;